"""update price column to decimal in products

Revision ID: 6ebc966ec598
Revises: a2d1e1f78988
Create Date: 2026-01-12 17:12:55.271851

"""
from typing import Sequence, Union
import sqlalchemy as sa
from alembic import op


revision: str = '6ebc966ec598'
down_revision: Union[str, Sequence[str], None] = 'a2d1e1f78988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.alter_column('products', 'price',  #pylint: disable=no-member
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price', #pylint: disable=no-member
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=False)

