@baseUrl =http://localhost:8000/api/v1/users
# INVALID USER CREATION WITH ALL FIELDS WRONG
POST {{baseUrl}}
Content-Type: application/json

{
    "first_name": "Jo",
    "last_name": "Silva",
    "age": 15,
    "email": "invalid-email",
    "phone": "12345",
    "username": "js",
    "password": "weakpass"
}


### CREATING A VALID USER
POST {{baseUrl}}
Content-Type: application/json

{
    "first_name": "João",
    "last_name": "Silva",
    "age": 25,
    "email": "joao.silva@example.com",
    "phone": "11999999999",
    "username": "joaosilva",
    "password": "StrongP@ssw0rd!"
}

### CREATING A USER WITH AN EMAIL THAT ALREADY EXISTS
POST {{baseUrl}}
Content-Type: application/json

{
    "first_name": "Maria",
    "last_name": "Oliveira",
    "age": 30,
    "email": "joao.silva@example.com",
    "phone": "11988888888",
    "username": "mariaoliveira",
    "password": "An0ther$trongPass!"
}


### TESTING WEEK PASSWORD
POST {{baseUrl}}
Content-Type: application/json

{
    "first_name": "Carlos",
    "last_name": "Santos",
    "age": 28,
    "email": "carlos.santos@example.com",
    "phone": "11977777777",
    "username": "carlossantos",
    "password": "weakpass"
}